### ISSUE TITLE
Feature wish: add a command line option for getting a list of tube lines in that particular town.

### ISSUE THREAD

**Issue by gwselke** [manwar/Map-Tube-CLI#1]
It is sometimes hard to guess exactly which names have been employed for the map data -- this goes for lines and for stations.
`map-tube --map=xxx --line=yyy --line_mappings`
is a nice way to find the exact names of stations if one knows the line name (indicated by `yyy `above).
But as far as I can tell there is no easy way (apart from peeking into the XML or JSON file) to find the names of the lines.

My feature wish would be a new command line option, say, `--list_lines` which would just show a list of line names (sorted alphabetically) in that particular tube network.

**Comment by manwar** [comment]
Nice suggestion @gwselke

**Comment by gwselke** [comment]
Great work, @manwar - thank you from a happy user!

**Comment by manwar** [comment]
Closing the issue now.
